# Default values for Gradle projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: registry.ng.bluemix.net/dragoonsbets/drgmsuser
  tag: 0.0.36
  pullPolicy: IfNotPresent
service:
  name: drgmsuser
  type: ClusterIP
  portName: http
  externalPort: 80
  internalPort: 8081
  annotations:
    fabric8.io/expose: "true"
    fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: nginx"
resources:
  limits:
    cpu: 1
    memory: 3Gi
  requests:
    cpu: 500m
    memory: 1Gi
probePath: /management/health
livenessProbe:
  initialDelaySeconds: 120
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  periodSeconds: 15
  successThreshold: 1
  timeoutSeconds: 1
  failureThreshold: 6
  initialDelaySeconds: 20
terminationGracePeriodSeconds: 10
postgresql:
  enabled: true
  postgresUser: drgmsuser
  postgresDatabase: drgMsUser
  pgHbaConfiguration: "host all drgmsuser all trust"
